include $(GL4ES_PATH)/Android.mk
include $(SUPPORT_LIBS)/SDL2/SDL2/Android.mk
include $(SUPPORT_LIBS)/SDL2/SDL2_mixer/Android.mk
include $(SUPPORT_LIBS)/jpeg8d/Android.mk
include $(SUPPORT_LIBS)/libzip/Android.mk
include $(SUPPORT_LIBS)/libpng/Android.mk
include $(SUPPORT_LIBS)/sigc++/Android.mk
include $(TOP_DIR)/quake2/Android.mk
include $(TOP_DIR)/quake2/Android_game.mk
include $(TOP_DIR)/quake2/Android_gl1.mk
