

#define qglBegin glBegin
#define qglEnd glEnd
#define qglEnable glEnable 
#define qglDisable glDisable 
#define qglVertex2f glVertex2f
#define qglColor3f glColor3f
#define qglTexCoord2f glTexCoord2f
#define qglViewport glViewport 
#define qglLoadIdentity glLoadIdentity 
#define qglColor4f glColor4f 
#define qglOrtho glOrtho 
#define qglMatrixMode glMatrixMode 
#define qglTexParameterf glTexParameterf 
#define qglTexImage2D glTexImage2D 
#define qglDrawBuffer glDrawBuffer
#define qglTranslatef glTranslatef 
#define qglRotatef glRotatef 
#define qglScalef glScalef 
#define qglDepthRange glDepthRange
#define qglDepthFunc glDepthFunc 
#define qglFinish glFinish 
#define qglGetFloatv glGetFloatv 
#define qglGetIntegerv glGetIntegerv 
#define qglCullFace glCullFace 
#define qglFrustum glFrustum 
#define qglClear glClear 
#define qglVertex3f glVertex3f
#define qglColor4fv glColor4fv
#define qglHint glHint 
#define qglBlendFunc glBlendFunc 
#define qglPopMatrix glPopMatrix 
#define qglShadeModel glShadeModel 
#define qglPushMatrix glPushMatrix 
#define qglTexEnvf glTexEnvf 
#define qglVertex3fv glVertex3fv
#define qglDepthMask glDepthMask 
#define qglBindTexture glBindTexture 
#define qglGetString glGetString
#define qglAlphaFunc glAlphaFunc 
#define qglFlush glFlush 
#define qglReadPixels glReadPixels 
#define qglReadBuffer glReadBuffer
#define qglLoadMatrixf glLoadMatrixf 
#define qglTexSubImage2D glTexSubImage2D 
#define qglClearColor glClearColor 
#define qglGetError glGetError 
#define qglActiveTexture glActiveTexture 
#define qglClientActiveTexture glClientActiveTexture 
#define qglColor3ubv glColor3ubv
#define qglPolygonMode glPolygonMode
#define qglArrayElement glArrayElement
#define qglLineWidth glLineWidth
#define qglCallList glCallList
#define qglTexCoord2fv glTexCoord2fv
#define qglColorMask glColorMask
#define qglStencilFunc glStencilFunc
#define qglStencilOp glStencilOp
#define qglColor4ubv glColor4ubv
#define qglDrawElements glDrawElements
#define qglEnableClientState glEnableClientState
#define qglDisableClientState glDisableClientState
#define qglVertexPointer glVertexPointer
#define qglTexCoordPointer glTexCoordPointer
#define qglColorPointer glColorPointer
#define qglPolygonOffset glPolygonOffset
#define qglClearDepth glClearDepth
#define qglDeleteTextures glDeleteTextures
#define qglTexParameterfv glTexParameterfv
#define qglStencilMask glStencilMask
#define qglClearStencil glClearStencil
#define qglScissor glScissor
#define qglClipPlane glClipPlane
#define qglColor3fv glColor3fv
#define qglPointSize glPointSize
#define qglMultiTexCoord2fARB glMultiTexCoord2fARB



